### ISSUE TITLE
Issue in Python 2.7 

### ISSUE THREAD

**Issue by sks147** [The-Maverick-Meerkat/Website-Scanner#1]
```
1. import urllib
2. import io
3. def get_robots_txt(url):
4.     if url.endswith('/'):
5.         path = url
6.     else:
7.         path = url + '/'
8.     req = urllib.urlopen(path + 'robots.txt', data=None)
9.     data = io.TextIOWrapper(req, encoding='utf-8')
10.     return data.read()
```

In this function I have been trying to get it working on python 2.7 version but I am getting some error

```
WARNING: No targets were specified, so 0 hosts scanned.
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    gather_info('thenewboston.com', 'https://www.thenewboston.com/')
  File "main.py", line 16, in gather_info
    r_txt = robots_txt.get_robots_txt(url)
  File "/webinfo/robots_txt.py", line 11, in get_robots_txt
    data = io.TextIOWrapper(req, encoding='utf-8')
AttributeError: addinfourl instance has no attribute 'readable'
```
